### ISSUE TITLE
Add ability to specify different network device

### ISSUE THREAD

**Issue by dsine-de** [pm2-hive/pm2-server-monit#11]
My VPS uses not "eth0" as its network interface name but "venet0". Could you add an option in the future to be able to specify the network interface name please?

**Comment by dsine-de** [comment]
To be a bit more clear, the "venet0" input and output is visible on the Keymetrics interface, but only as text - the bigger boxes with graphs try to read "eth0". The tooltip also reads "NaN" when I mouseover the graph line.

**Comment by alavit-d** [comment]
Changed in [v2](https://github.com/pm2-hive/pm2-server-monit/tree/v2.0/): The main probe are net in / net out, the sum of all network connections detected.

Every detected connection is still monitored individually in the dashboard in the smaller boxes.

Cheers
