### ISSUE TITLE
To much processes spawned

### ISSUE THREAD

**Issue by adrian-ludwig** [pm2-hive/pm2-server-monit#13]
Yesterday we had problem on production servers with pm2-server-monit.
This module spawned over 600+ `df -k` processes and not killed them.
We had to remove module and kill processes manualy.

**Comment by jshkurti** [comment]
Thanks for reporting this :)
I'm going to have a look at it.

**Comment by jshkurti** [comment]
What happens when you manually type `df -k` in your terminal though ?

**Comment by adrian-ludwig** [comment]
I get output of like ~100 disks mounted :)
