### ISSUE TITLE
Can't start: Error: spawn ENOENT

### ISSUE THREAD

**Issue by aliksend** [pm2-hive/pm2-server-monit#14]
Hi. 
I have CentOS 7 on my VDS and I have been installed pm2 and pm2-server-monit. But I have this errors in my log:
```
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
14 times with status `errored` in `pm2 list` and number 14 in `restarts` column.
What I need to do? I know that this tool is working on `ubuntu 14.04` on this VDS. May be I have some unresolved dependencies?
Thank you for your attention

**Comment by jshkurti** [comment]
pm2-server-monit is the app crashing, right ?

**Comment by aliksend** [comment]
Yes, status of pm2-server-monit is `errored` and it's don't working.
My nodejs app and pm2-logrotate working good, but this tool not.

**Comment by jshkurti** [comment]
Can you try uninstalling and reinstalling pm2-server-monit ?
`pm2 uninstall pm2-server-monit;pm2 install pm2-server-monit`

**Comment by aliksend** [comment]
Yes, I already tried it and I tried again just now. Nothing changed
![2015-08-18 23 12 04](https://cloud.githubusercontent.com/assets/4923699/9341450/9a2d5332-45fe-11e5-885c-2371b9e81f23.png)

**Comment by alpertayfun** [comment]
Anyone solve this ? We are gettin' like errors. What we gonna do ? Logs not understable.

**Comment by cinderblock** [comment]
I had an issue of pm2 not starting because my OS has `/bin/ifconfig` and no `/sbin/ifconfig`. I had to hack the source files in `node_modules` to get it to work.

Could we add a config variable to set this path?

Are there other commands that don't work on all OSes or that need su? I'm running as a dedicated pm2 user. My `pm2-server-monit-error.log` has some other errors:

```
Error: 1
    at /var/lib/pm2/node_modules/pm2-server-monit/lib/os.js:35:26
    at /var/lib/pm2/node_modules/shelljs/src/exec.js:172:7
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
exec: internal error
exec: internal error
exec: internal error
exec: internal error
exec: internal error
[...]
```

**Comment by marcelboettcher** [comment]
Had the same issue in docker image node:4.4.6

ifconfig is not used in new debian releases anymore. Installing it fixed it for me:

sudo apt-get update
sudo apt-get install net-tools

**Comment by alavit-d** [comment]
@cinderblock: Used shelljs for more compatibility with ifconfig location

@marcelboettcher: Added ifconfig as requirement in the Readme, thanks!

This module heavily relies on a set of commonly used commands on unix distributions. If this still crashes on your system with version 2.x+ and ifconfig installed, please open a new ticket with detailed system information.

Cheers
