### ISSUE TITLE
`Error: 1` on launch

### ISSUE THREAD

**Issue by eTorAken** [pm2-hive/pm2-server-monit#16]
This does not seem to affect the process nor its features (my keymetrics.io shows me all server-monit informations I want), but I got this log in pm2 everytime I'm starting the pm2-server-monit:
```
pm2-server-monit-26 Error: 1
    at /home/dev/.pm2/node_modules/pm2-server-monit/lib/os.js:35:26
    at /home/dev/.pm2/node_modules/pm2-server-monit/node_modules/shelljs/src/exec.js:142:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by alavit-d** [comment]
This usually appears when we could not determine which OS you are running on, do you see anything appear in the Operating System widget?

**Comment by eTorAken** [comment]
That's right, the OS widget show `N/A`. What could be the cause?

**Comment by alavit-d** [comment]
We only detect the most common linux distributions atm (Debian, Ubuntu, CentOS, Red Hat). What are you using?

**Comment by eTorAken** [comment]
Ubuntu 14.04.3 LTS

**Comment by alavit-d** [comment]
Im on the same version and it seems to be working for me, is the output of `cat /etc/issue -e` like this?
```
Ubuntu 14.04.3 LTS \n \l$
$
```

**Comment by eTorAken** [comment]
The file is empty, it seems the installation process used by our provider (OVH) is the cause of it (http://www.virtualmin.com/node/33336). Here is the workaround I used to get it back:
```sh
$ cp /etc/issue.net /etc/issue
$ cat /etc/issue -e
Ubuntu 14.04.3 LTS$
```

It works now :) Thank you
