### ISSUE TITLE
Low memory warning does not accurately reflect the threshold which has been set

### ISSUE THREAD

**Issue by lklepner** [pm2-hive/pm2-server-monit#20]
When the low memory threshold is adjusted from the 10% default to a custom value of 30% the error message generated by the system reads:  

"Less than 10% memory available 30"

Ideally this message would more clearly state the event which occurred. "Less than 30% memory available".

**Comment by roccomuso** [comment]
+1

**Comment by alavit-d** [comment]
Removed custom messages and let the default one for more flexibility: 
`Probe [probe name] has reached value [threshold]`
If you feel like more details should be given, please open an issue in the [pmx repo](https://github.com/keymetrics/pmx)

Cheers
