### ISSUE TITLE
Wrong disk usage 

### ISSUE THREAD

**Issue by satazor** [pm2-hive/pm2-server-monit#21]
I have some VPS on [scaleway](http://scaleway.com) and pm2-server-monit reports 100% available disk at all times.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
none            3.9G     0  3.9G   0% /dev
tmpfs           795M   22M  773M   3% /run
/dev/nbd0        46G   12G   32G  27% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
```

As you see, the primary disk is mounted in `/dev/nbd0` which is 27% used.

**Comment by lucky-libora** [comment]
As I understand problem is in lib/drive.js:23

      var disk_info = lines[0];

This code parse info about first disk from df -k

Is it possible to set up disk name in config?

**Comment by satazor** [comment]
Nop, not that I know of

**Comment by alavit-d** [comment]
Fixed in [v2](https://github.com/pm2-hive/pm2-server-monit/tree/v2.0):
Now follows `/` by default, you can set to whatever mounted drive you want.
Please note this will refer to the `Mounted on` column, not the `Filesystem` one.

Cheers

**Comment by lucky-libora** [comment]
thnx a lot
