### ISSUE TITLE
exec: internal error

### ISSUE THREAD

**Issue by oliversalzburg** [pm2-hive/pm2-server-monit#23]
My `pm2-server-monit-error-10.log` log file is littered with the message above. No other useful output beside it.

**Comment by jeveloper** [comment]
Curious if you resolved this?

does it need to be sudo pm2 install ... ?

**Comment by oliversalzburg** [comment]
No, I didn't solve this. The log continues to be filled with the message.

pm2 *is* running as root. Because I found no real indication regarding this matter in the docs, I assumed I let it run as root and it would setuid to a less privileged account, which it doesn't do. So either it requires root or it's not capable to lowering to a less privileged account. Neither would surprise me.

**Comment by alavit-d** [comment]
Hi,

This indicates one of the commands we use fails on your system. This could come from ifconfig not being installed by default on your server. If this still happens with the latest version and ifconfig installed, could I have your detailed system information?

Thanks

**Comment by oliversalzburg** [comment]
Sorry, I stopped using these pm2 features due to extremely poor response times from developers and support.
