### ISSUE TITLE
pm2 processes ? (question mark) on left side, beside process name

### ISSUE THREAD

**Issue by m-menon** [pm2-hive/pm2-server-monit#24]
I have installed pm2 and it all went on fine. But I see a few question (?) marks when I run pm2 monit which I don't really understand what it means. I have set up the monitoring server too, as specified in https://app.keymetrics.io console.

```
? PM2 monitoring (To go further check out https://app.keymetrics.io)

? pm2-server-monit                    [                              ] 0 %
[0] [fork_mode]                        [|||||                         ] 31.375 MB

? index                               [                              ] 0 %
[1] [cluster_mode]                     [||||||||                      ] 47.734 MB

? index                               [                              ] 0 %
[2] [cluster_mode]                     [||||||||                      ] 47.398 MB

? index                               [                              ] 0 %
[3] [cluster_mode]                     [||||||||                      ] 46.418 MB
```

The question marks that I am referring to are the ones in front of "index" e.g "**? index**"
I can see from some of the other screenshots on the web that it is supposed to be either a green or red circle. I have no idea as to what those circles are. Anyone can help me understand?

Thanks,
M.M

**Comment by alavit-d** [comment]
Hi,

This is supposed to be a green circle if the application is live or a red if it crashed.
It seems the display failed on your terminal for some reason. What terminal do you use?
Those green/red circles can also be found in the Keymetrics console, right next to the application name.

Hope this helps!

**Comment by soyuka** [comment]
It's a known issue https://github.com/Unitech/pm2/issues/727 and related
