### ISSUE TITLE
pm2-server-monit TypeError.

### ISSUE THREAD

**Issue by soyuka** [pm2-hive/pm2-server-monit#25]
This is part of the email reporting an error regarding pm2-server-monit agent.

Application: pm2-server-monit
Message:
TypeError: Cannot read property 'replace' of undefined
at /root/.pm2/node_modules/pm2-server-monit/lib/drive.js:22:35
at ChildProcess.exithandler (child_process.js:742:7)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Socket. (child_process.js:1183:11)
at Socket.emit (events.js:107:17)
at Pipe.close (net.js:485:12)

Import from https://github.com/Unitech/pm2/issues/2284

**Comment by roccomuso** [comment]
Moreover, I'm encountering serious memory leak issue.
How pm2-server-monit can consume almost 250Mb (24%) on a 1Gb Raspberry Pi?

![memory consumption](https://cloud.githubusercontent.com/assets/6730217/16911607/c5424bfc-4cdf-11e6-989f-9816b07b872e.png)

**Comment by alavit-d** [comment]
Used shelljs + added new check in [v2](https://github.com/pm2-hive/pm2-server-monit/tree/v2.0). Please reopen if the error appears again.

About the memory leak: `pm2-server-monit` usually consumes 25-35 Mo, and I could not observe a memory leak over time. It also has a hard limit set at 150Mo and pm2 will restart it if it goes over this level. If you still have a leak with the new pm2 version, please open a new issue

Cheers
