### ISSUE TITLE
Cannot change DRIVE. Always monitors first drive

### ISSUE THREAD

**Issue by acedward** [pm2-hive/pm2-server-monit#26]
The drive I want to monitor appears second.
Looking thought the code, the drive been monitored is hard coded to [1] 
So the monitor was looking a udev instead of /dev/xvda1

    > df -h
    Filesystem      Size  Used Avail Use% Mounted on 
    udev            2.0G   12K  2.0G   1% /dev   
    /dev/xvda1      7.8G  6.0G  1.4G  82% /

Ideally we should be able to configure the monitor through the configuration file:
`> pm2 set pm2-server-monit:drive /dev/xvda1`

**Comment by alavit-d** [comment]
Fixed in [v2](https://github.com/pm2-hive/pm2-server-monit/tree/v2.0):
Now follows `/` by default, you can set to whatever mounted drive you want.
Please note this will refer to the `Mounted on` column, not the `Filesystem` one.

Cheers
