### ISSUE TITLE
ifconfig not available as non-root user

### ISSUE THREAD

**Issue by satazor** [pm2-hive/pm2-server-monit#27]
I've setup pm2 to a non-root user for security reasons. The issue is that `ifconfig` is not available to this user because `/sbin` is not on his path and I would like to keep it that way.

Is there any solution to this problem, e.g.: passing PATH env to pm2 or adding a config to specify the path to ifconfig?

Thanks

**Comment by TadeoArmenta** [comment]
as root :
mkdir /nonroot ; ln /sbin/ifconfig /nonroot/ifconfig

as your non privileged user:
edit ~/.profile and add to the bottom this line:

export PATH=$PATH:/nonroot

reboot or use source ~/.profile and your done

**Comment by satazor** [comment]
Thats a possible solution, still I'm exposing ifconfig for every program of this user. I got several services under this user, which means ifconfig is available to all of them.

Passing PATH to pm2-server-monit was a bit better, any way to do that?

**Comment by TadeoArmenta** [comment]
Note that only non-root users can only get/read interface data, but not set/write it. Setting interface parameters as a non-root user will generate errors

Example:

$ ifconfig eth0 192.168.0.155
SIOCSIFADDR: Permission denied
SIOCSIFFLAGS: Permission denied


I think that currently server monit doesn't have a way to pass the path to ifconfig, however, I think this cant be difficult.

**Comment by satazor** [comment]
@TadeoArmenta I know, thanks for your feedback. I will go with your solution for now.
