### ISSUE TITLE
disk name invalid

### ISSUE THREAD

**Issue by TadeoArmenta** [pm2-hive/pm2-server-monit#28]
Server monit is constantly reporting "disk name invalid", but all the disks are aparently ok, even in keymetrics.io on the dashboard, when i click on "disk usage" button, it reports all the mount points with normally.

**Comment by AlexandreAWE** [comment]
+1 I only use MongoDB on the sever

**Comment by alavit-d** [comment]
v2.2.0+: if no match to the string in the configuration is found, the module will automatically default to `/` and it it fails to do so it will output in the error.

Do you still experience this issue?

**Comment by AlexandreAWE** [comment]
I upgrade the package. Seem good now!
Thanks

**Comment by alavit-d** [comment]
:ok_hand:
