### ISSUE TITLE
Network In/Out showing N/A

### ISSUE THREAD

**Issue by eyonov** [pm2-hive/pm2-server-monit#29]
On my Keymetrics console, I'm not getting any data for Net in or out. Is there a config change that I'm missing? Client is CentOS 7.2.

Thank you

**Comment by aembke** [comment]
Seeing the same with Ubuntu 14.04.

**Comment by alavit-d** [comment]
Fixed by using ip instead of ifconfig v2.2.0+

**Comment by silverhawk184** [comment]
I am getting the same issue on Debian 8.
