### ISSUE TITLE
Fail: could not retrieve user/lsof metrics

### ISSUE THREAD

**Issue by stephen-last** [pm2-hive/pm2-server-monit#30]
I have `pm2` and `pm2-server-monit` running on a Windows Server 2012 R2 machine.

I am seeing these issues/errors:

> Fail: could not retrieve lsof metrics
> Fail: could not retrieve user metrics

The number just keeps going up and I can't find any information on them.

It also says:

> Infected deployments: Server infected

What does this mean and how do I fix it..?

**Comment by alavit-d** [comment]
The module is trying to retrieve unix-specific values and fails on windows. As of yet it is not designed to offer full windows support

**Comment by nicolas-despres** [comment]
I got the same issue today. Do you have any plan for a windows support? Thank you
