### ISSUE TITLE
I Cannot uninstalled or run anything

### ISSUE THREAD

**Issue by ayxos** [pm2-hive/pm2-server-monit#31]
´´´
➜  interpretaMe git:(master) ✗ pm2 uninstall pm2-server-monit
[PM2] Spawning PM2 daemon
[Keymetrics.io] Using (Public key: xxx) (Private key: xxx)
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
[PM2] PM2 Successfully daemonized
[PM2][Module] Starting module pm2-server-monit
[PM2][WARN] Applications pm2-server-monit not running, starting...
´´´

**Comment by vmarchaud** [comment]
Please follow the issue template to describe your problem.

**Comment by vmarchaud** [comment]
What's the problem exactly ? Can you explain a little bit more ?

**Comment by ayxos** [comment]
Every single command with pm2 tries to connect with keymetrics and gets starting pm2-server-monit. I cannot run not even 'delete' or 'uninstall'.

At the end i kill the process after destroy my KM server.

**Comment by vmarchaud** [comment]
Do you have a way to reproduce the issue ? 
Try to a `npm install -g pm2 && pm2 update`

**Comment by ayxos** [comment]
I have a DO droplet, i restarted it, after that moment on `pm2-server-monit` plugin freezes the whole execution for every single pm2 command available (including `npm install -g pm2 && pm2 update`) displaying my first msg output. 

At the end i removed manually `rm ~/.pm2/agent.json` to destroy the link between pm2 and keyMetrics and then i was able to remove `pm2-server-monit`.

Really weird
