### ISSUE TITLE
failing to start at all if ifconfig is not available for the user

### ISSUE THREAD

**Issue by sheershoff** [pm2-hive/pm2-server-monit#32]
on Debian by default ifconfig is in sbin, so it's visible to root user only.

while the requirement is listed, it'll be good to:
1. not to fail at all if the ifconfig is not available
2. add the recommendation: `sudo ln -s /sbin/ifconfig /bin/ifconfig`

**Comment by alavit-d** [comment]
Now using ip via `ip -s link` and outputing the error via console.error().

Cheers
