### ISSUE TITLE
how use

### ISSUE THREAD

**Issue by kivervinicius** [pm2-hive/pm2-server-monit#33]
I did not find information on how to use it

**Comment by vmarchaud** [comment]
Informations are automatically reported to the keymetrics dashboard, there isn't any way to "use it" apart from using keymetrics.

**Comment by kivervinicius** [comment]
thanks

**Comment by michael-ts** [comment]
Oh well that's nice.  I just commented on another issue reporting of this exact same problem.  This really should be documented better.  The README says nothing about needing Keymetrics, just how to install this cool looking module that apparently does nothing when you install it. :-(
