### ISSUE TITLE
how to use the module

### ISSUE THREAD

**Issue by h2y** [pm2-hive/pm2-server-monit#36]
![](https://github.com/pm2-hive/pm2-server-monit/raw/master/server-monit.png)

😢 
I dont know how to enter this interface, after install module.

**Comment by h2y** [comment]
use [https://app.keymetrics.io]()

I konw...

**Comment by michael-ts** [comment]
I am having this problem too, there does not appear to be any [documentation](https://github.com/pm2-hive/pm2-server-monit/blob/master/README.md) on how to bring up the monitor once you have it installed.

I don't understand the solution you found, plus your link doesn't match the text.  When I click on the link, it brings me to this page, but if I manually copy that URL and paste it into a new window, it takes me to a login page I don't recognize.  I see no mention in the documentation on any other dependencies (like this login screen) to getting this to work.

**Comment by michael-ts** [comment]
By the way, when I installed this on OS X nothing happened.  When I tried to install it under Windows 10, I got a periodic spawn of what appeared to be three or four windows that flashed on the screen and then disappeared, just fast enough to make it about impossible to do anything until I could uninstall everything.  (Strangely, I could still type in the command prompt window, but I couldn't switch to another window so I had to get the instructions on how to uninstall from another device!)

**Comment by h2y** [comment]
- this is amodule for pm2.
- keymetrics.io is a official monit server by pm2.
- this module is one of the monit components.

So, you should sign up in keymetrics.io, get a bind code next.
Then input that  code in pm2 which had install this module.
