### ISSUE TITLE
Double check all issues with exec internal errors

### ISSUE THREAD

**Issue by Unitech** [pm2-hive/pm2-server-monit#48]
@vmarchaud @f-hj 

Many users complains in the Zendesk support about exec internal errors. We have to list these issues on this repository

**Comment by vmarchaud** [comment]
I had the error in my prod server, an update fixed them.

**Comment by geoffjukes** [comment]
"an update fixed them" - an update of what....? I am having the same issue

**Comment by vmarchaud** [comment]
An update of the module, just re-install to get the last version

**Comment by geoffjukes** [comment]
weird. I only installed it today, but I did as suggested, lo-and-behold, no more syslog spam! Thanks @vmarchaud

**Comment by Unitech** [comment]
Ok it means a restart.
Restart is not a way to fix these errors
We need to inspect more where this error comes from
