### ISSUE TITLE
Committing semi space failed. Allocation failed

### ISSUE THREAD

**Issue by malipraful** [pm2-hive/pm2-server-monit#50]
0|pm2-serv | exec: internal error
0|pm2-serv | FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

**Comment by vmarchaud** [comment]
Could you try with the latest update ? `pm2 install pm2-server-monit`

**Comment by malipraful** [comment]
yes sir21.03.2017, 15:59, "vmarchaud" <notifications@github.com>:Could you try with the latest update ? pm2 install pm2-server-monit

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Thanks & Regards,Mali Praful
