### ISSUE TITLE
/etc/issue empty , pm2 not working

### ISSUE THREAD

**Issue by laurentdebricon** [pm2-hive/pm2-server-monit#52]
Ubuntu 14.04 LTS , ovh.fr installed
/etc/issue was empty so os detection failed , then crash to a redhat file.

Error: Error: ENOENT: no such file or directory, open '/etc/redhat-release'
17|pm2-ser |     at ReadFileContext.callback (/home/auto/.pm2/node_modules/pm2-server-monit/lib/os.js:30:26)
17|pm2-ser |     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

I fixed the issue with manual editing /etc/issue and putting "Ubuntu 14.04.5 LTS"

**Comment by vmarchaud** [comment]
Salut Laurent,
Merci du report, on va s'en occuper :)

**Comment by vmarchaud** [comment]
Resolved with https://github.com/pm2-hive/pm2-server-monit/commit/34bb9163572f1b081a33c1f2d25c34bb3cc2dda8 under version `2.5.1`.
