### ISSUE TITLE
no free/used disk space

### ISSUE THREAD

**Issue by giulianozorzi** [pm2-hive/pm2-server-monit#53]
Hi,
I'm unable to get the free/used disk space stats.
Drive param is / (I tried /opt too as this is the disk I'd like to monitor)
the disk usage command from the dashboard outputs
[+] Response has been successfully received:

File system     Dim. Usati Dispon. Uso% Montato su
/dev/sda1        10G  4,3G    5,8G  43% /
devtmpfs        7,4G     0    7,4G   0% /dev
tmpfs           7,4G  4,0K    7,4G   1% /dev/shm
tmpfs           7,4G  729M    6,7G  10% /run
tmpfs           7,4G     0    7,4G   0% /sys/fs/cgroup
/dev/sdb1        69G   19G     47G  29% /opt
tmpfs           1,5G     0    1,5G   0% /run/user/1001

module is the latest as today (apr 12th 2017)

in the logs I see lots of 
disk name invalid and /  not found
but not in the last 2 hours

thanks

g

**Comment by f-hj** [comment]
Hi,
pm2-server-monit use english language to parse `df` like this
```
Filesystem     1024-blocks     Used Available Capacity Mounted on
udev               6092628        0   6092628       0% /dev
tmpfs              1222564    62764   1159800       6% /run
/dev/sda2        102424904 72201512  24997460      75% /
tmpfs              6112804   109888   6002916       2% /dev/shm
tmpfs                 5120        4      5116       1% /run/lock
tmpfs              6112804        0   6112804       0% /sys/fs/cgroup
/dev/sda1           523248     3540    519708       1% /boot/efi
tmpfs              1222564      116   1222448       1% /run/user/1000
```
You can switch your system language to english or make a PR with multi language support.

**Comment by giulianozorzi** [comment]
ok, thanks

**Comment by giulianozorzi** [comment]
I changed drive.js line 10 to

  cp.exec('export LANG=en_US.UTF-8; df -kP', { shell: true }, function(err, out) {

not the best solution but it should work :)
