### ISSUE TITLE
CentOS 6.9 gets reported as Ubuntu 14.04

### ISSUE THREAD

**Issue by FreakenK** [pm2-hive/pm2-server-monit#58]

**Comment by f-hj** [comment]
Hello,

I cannot reproduce your issue with *CentOS release 6.9 (Final)*.
Can you `cat /etc/issue`, `uname -a` and send me result?

Thank you.

**Comment by FreakenK** [comment]
Nevermind, there probably was a bug on the Keymetrics interface that has now been fixed. I see the correct distro now.
